/**
 * Manifest pro ScrollTelling na /o-mne. Redakční pravidla: fakta jen ta,
 * která už jsou doložena jinde na webu nebo v citovaných médiích; žádné
 * superlativy bez důkazu (Stanford Web Credibility); obranu proti výtkám
 * řeší FAQ – životopis ji nepředjímá.
 */
export const aboutStory = [
  "Dobrý den. Jmenuji se Radko Sáblík, narodil jsem se 1. března 1962 v Praze a celý profesní život jsem zasvětil jedné myšlence: dokázat, že škola nemusí fungovat jako zkostnatělý úřad. Studenti pro mě nikdy nebyli pasivní nádoby, do kterých se nalévá učivo. Jsou to partneři a spolutvůrci svého vlastního vzdělávání.",
  "Původní profesí jsem strojní inženýr. Po Gymnáziu Botičská jsem vystudoval Fakultu strojní ČVUT a později si doplnil pedagogické vzdělání a školský management na Univerzitě Karlově. Inženýrský přístup mě naučil dívat se na školu ne jako na neměnnou hierarchii, ale jako na živý systém, který je potřeba neustále ladit, zlepšovat a nebát se ho prověřovat.",
  "Druhou školou života mi byl sport. Dvacet let jsem vedl Sokol Motol, šestnáct let Pražský basketbalový svaz, trénoval jsem mládež i dospělé a jako rozhodčí pískal první ligu. Sport mě naučil rychle se rozhodovat pod tlakem. A hlavně jednu zásadní věc: chcete-li respekt, musíte ho nejdřív sami dávat.",
  "Když jsem 1. listopadu 2002 poprvé otevřel dveře ředitelny Smíchovské střední, dal jsem si dva na první pohled bláznivé cíle: dostat školu do TOP 10 v republice a udělat ze studentů naši absolutní prioritu. Tradiční rakousko-uherský model školství – továrna na poslušné a průměrné zaměstnance – je totiž v 21. století překonaný.",
  "Začali jsme bourat bariéry mezi katedrou a lavicemi a předávat studentům skutečnou odpovědnost. Náš přístup stojí na pěti podmínkách: nebát se předat zodpovědnost, probouzet vnitřní motivaci, dávat prostor talentu, studenty aktivizovat a podporovat jejich podnikavost.",
  "Dnes to u nás vidíte na každém kroku. Školní IT spravují sami studenti: mají smlouvy a vlastní rozpočty. Studenti vedou PR, vydávají časopis Presloviny a provozují mediální dům, který vysílá konference pro tisíce diváků. Téměř polovinu učitelského sboru tvoří naši mladí absolventi a ti nejlepší studenti vedou semináře pro mladší spolužáky.",
  "Škola ale nesmí být odtržená od reality. Proto jsme přímo na nádvoří postavili coworkingové centrum Next Zone se startupovým inkubátorem. U střední školy je to věc v Česku ojedinělá. Sídlí v něm desítky studentských firem a projektů. Mladí lidé u nás můžou bezpečně zkoušet, padat, poučit se a uspět dřív, než dostanou maturitní vysvědčení.",
  "V AI laboratoři studenti trénují vlastní modely umělé inteligence a programují humanoidní roboty. Ve Vesmírné akademii koordinují projekty s Ministerstvem dopravy a svůj výzkum jezdí prezentovat na univerzity jako Berkeley nebo MIT. Nemusíme se smířit s rolí levné pracovní síly. Budujeme mozkovnu, ne montovnu.",
  "Jako první škola v Česku jsme otevřeli středoškolský obor kybernetické bezpečnosti. Vedou ho naši absolventi a jejich tréninkovou platformu dnes používají desítky škol. Naše týmy vyhrávají celostátní soutěže a hackathony a několikrát jsme získali ocenění Kyber organizace roku.",
  "Zkušenosti jsem sepsal v knize Učit jde i jinak, letos jsem vydal její pokračování. Podílel jsem se jako expert na národní Strategii vzdělávání 2030+, radil jsem dvěma ministrům školství a založil Unii Škol Inovativních. To proto, aby se náš přístup – třeba model 4+1 s jedním dnem řízeného samostudia týdně – šířil po celé republice.",
  "Vím ale i to, že technologie a dokonalá organizace bez etiky dokážou být zbraní. Proto jsem napsal trilogii Když přišel čas zabíjení a dokumentární svazek Továrna na smrt, kde popisuji historii vyhlazovacího tábora v Osvětimi. Špičkové vzdělání musí jít ruku v ruce s lidskostí a občanskou etikou. Efektivita bez svědomí vytváří monstra.",
  "Chuť měnit věci mě přivedla i do komunální politiky. Za ODS jsem byl místostarostou a zastupitelem v Mníšku pod Brdy a poznal jsem, jak umí systém svazovat ruce aktivním lidem. A pak, na jaře 2025, přišla největší výzva mého života: moji studenti z druhého ročníku přišli s tím, že bych měl kandidovat do Senátu. Že mi posbírají podpisy a udělají celou kampaň. Zjistili si dokonce, že můj dědeček byl senátorem už za první republiky.",
  "Když pak v listopadu přišla oficiální nabídka od ODS, bylo rozhodnuto. Jsem kandidátem strany. Ale především svých studentů. Kampaň jsem místo drahé agentury svěřil jim: od vizuální identity přes sociální sítě až po stánky v ulicích. Zapojují se dobrovolně, ve svém volném čase. Přesně tak, jak je celé roky učím: když ti něco dává smysl, jdi do toho. Nikdy předtím se nestalo, aby senátní kandidatura vzešla přímo z iniciativy studentů. A když se přidali Starostové a Lidovci, šel jsem do voleb jako společný kandidát tří demokratických stran.",
  "Do Senátu jdu s jasným cílem: promítnout smíchovskou efektivitu a zdravý rozum do celostátních zákonů. Stát nemá aktivním lidem házet klacky pod nohy. Chci jednodušší cestu pro podnikání mladých i dospělých, podporu sportu v regionech a propojování generací. Jako když naši studenti učí seniory zvládnout mobil, počítač i AI. Jeden senátor má omezené kompetence, ale kdo mě zná, ví, že nebudu sedět tiše v koutě. Kdo chce, hledá způsoby. Kdo nechce, hledá důvody.",
  "Společně to dokážeme. Díky.",
];
